# fly.toml app configuration file generated for docfinder on 2023-06-10T18:18:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "docfinder"
primary_region = "eze"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
