# fly.toml app configuration file generated for pps on 2023-06-09T10:27:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pps"
primary_region = "bog"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
